### PR TITLE
Fix PM2.5 values always reporting as 0

### LINKED ISSUE #9: No value for PM Sensor
Hi there,

First thanks a lot for doing this great work, it was one reason why i've choose the 300s purifier.
Flashing worked like a charm and i already linked it to my HA instance.

The only "problem" i have, but maybe this is an expected behavior, i only get a value for the PM Sensor if i turn on the fan with manual or auto mode. So why is this a problem for me: Cause i want to turn the purifier on if the PM Sensor is above some value, otherwise i would like to put it into sleep mode. Another option would be that you can set it to 0 at manual mode (not working, 0-1 is the same fan speed at manual mode)

If it's an expected behavior, maybe you have an idea how i can "hack" it to get the PM sensor values also if the fan is in sleep mode.

I think the fan sleep mode is using the deep sleep from the esp32. Not sure, however, maybe we could make another mode where the esp32 is still running, but the fan has just 1% power (or something above where you still don't hear the fan).

cheers
Christopher

### PR DESCRIPTION
**Pull request by Daemon125**
This patch corrects the PM2.5 value scaling logic for 300S/400S

Previously, the raw PM2.5 value was scaled using `(value * 10) / 10000`, which caused almost all real-world readings to truncate to zero due to integer division. As a result, Home Assistant always displayed 0.0 for PM2.5.

This fix removes the unnecessary division and scales the raw value with `(value * 10)` to align with the expected internal format used by the existing PM2.5 sensor logic.

The resulting values now match the 400S display and report correctly in Home Assistant. This was also tested and verified working with the 300S

Closes #9 
Partially addresses #18

### CODE REVIEW

**Comment by kerkmann** [comment]
I tried your fix with the `core 200s` but I am receiving `64512.0 µg/m³` which seems not. ^^"

**Comment by Daemon125** [comment]
> I tried your fix with the `core 200s` but I am receiving `64512.0 µg/m³` which seems not. ^^"

Interesting, I didn't have a 200S to test with. I assumed they'd have the same sensors, but it sounds like that one is way more accurate too. Guess we'll need to get model specific sensors in place for this.

**Comment by kerkmann** [comment]
> > I tried your fix with the `core 200s` but I am receiving `64512.0 µg/m³` which seems not. ^^"
> 
> Interesting, I didn't have a 200S to test with. I assumed they'd have the same sensors, but it sounds like that one is way more accurate too. Guess we'll need to get model specific sensors in place for this.

I am not sure if your division it part of the problem. It's hard for me to get good readings. Most of them report `6.4` or `0.0`, which makes no sense. I often see the following error messages:
```
01:39:18	[E]	[levoit:331][1;31m[ProcRxQueueTask][1;31m	
Received error response, ignoring packet
01:39:19	[W]	[levoit:612][1;31m[TxQueueTask][0;33m	
Timeout waiting for ACK for command CMD (0160a2): A5.22.07.07.00.EC.01.60.A2.CF.A6.1C.AA (13)
01:39:20	[E]	[levoit:331][1;31m[ProcRxQueueTask][1;31m	
Received error response, ignoring packet
01:39:22	[W]	[levoit:612][1;31m[TxQueueTask][0;33m	
Timeout waiting for ACK for command CMD (0160a2): A5.22.03.07.00.18.01.60.A2.13.00.00.00 (13)
```

But I am unable to find the root cause. Tried to increase the timeout, change the baudrate etc., maybe that's the reason and not your division. :(

**Comment by Daemon125** [comment]
> > > I tried your fix with the `core 200s` but I am receiving `64512.0 µg/m³` which seems not. ^^"
> > 
> > 
> > Interesting, I didn't have a 200S to test with. I assumed they'd have the same sensors, but it sounds like that one is way more accurate too. Guess we'll need to get model specific sensors in place for this.
> 
> I am not sure if your division it part of the problem. It's hard for me to get good readings. Most of them report `6.4` or `0.0`, which makes no sense. I often see the following error messages:
> 
> ```
> 01:39:18	[E]	[levoit:331]�[1;31m[ProcRxQueueTask]�[1;31m	
> Received error response, ignoring packet
> 01:39:19	[W]	[levoit:612]�[1;31m[TxQueueTask]�[0;33m	
> Timeout waiting for ACK for command CMD (0160a2): A5.22.07.07.00.EC.01.60.A2.CF.A6.1C.AA (13)
> 01:39:20	[E]	[levoit:331]�[1;31m[ProcRxQueueTask]�[1;31m	
> Received error response, ignoring packet
> 01:39:22	[W]	[levoit:612]�[1;31m[TxQueueTask]�[0;33m	
> Timeout waiting for ACK for command CMD (0160a2): A5.22.03.07.00.18.01.60.A2.13.00.00.00 (13)
> ```
> 
> But I am unable to find the root cause. Tried to increase the timeout, change the baudrate etc., maybe that's the reason and not your division. :(
> 
> Edit: The `TxQueueTask` is only happening after booting up the device. I think the `Timeout waiting for ACK for command CMD` is the root problem for reading corrent sensor data.

At least on mine it's just purely that /10000. The 400S has a screen with PM2.5 readout independent from the firmware, so I'm using that as a reference. I'm occasionally seeing that timeout error as well though. 

I just added some switches for device models, but it sounds like there might just be a bigger issue going on with the sensor in the 200S

File: components/levoit/levoit.cpp [hunk 1]
```diff
@@ -444,7 +444,19 @@ void Levoit::handle_payload_(LevoitPayloadType type, uint8_t *payload, size_t le
...
       if (!pm25NAN) {
         uint16_t raw_value = (payload[13] << 8) + payload[12];
-        uint32_t new_pm25Value = (raw_value * 10) / 10000;
+        
+        switch (this->device_model_) {
+          case LevoitDeviceModel::CORE_200S:
+            new_pm25Value = raw_value / 10000;
+            break;
+
+          case LevoitDeviceModel::UNKNOWN:
```
Comment (kerkmann) [inline components/levoit/levoit.cpp:453]:
```suggestion
```
There is no `UNKNOWN` btw. :)

File: components/levoit/levoit.cpp [hunk 2]
```diff
@@ -444,7 +444,19 @@ void Levoit::handle_payload_(LevoitPayloadType type, uint8_t *payload, size_t le
       pm25NAN = (payload[12] == 0xFF && payload[13] == 0xFF);
       if (!pm25NAN) {
         uint16_t raw_value = (payload[13] << 8) + payload[12];
-        uint32_t new_pm25Value = (raw_value * 10) / 10000;
+        
+        switch (this->device_model_) {
+          case LevoitDeviceModel::CORE_200S:
+            new_pm25Value = raw_value / 10000;
```
Comment (kerkmann) [inline components/levoit/levoit.cpp:450]:
```suggestion
            new_pm25Value = raw_value / 1000;
```
The old value was `10 times raw_value divided by 10000` which means `1000` and not `10000`. :)

**Review by kerkmann — CHANGES_REQUESTED** [review]

**Comment by kerkmann** [comment]
@Daemon125 
> At least on mine it's just purely that /10000. The 400S has a screen with PM2.5 readout independent from the firmware, so I'm using that as a reference. I'm occasionally seeing that timeout error as well though.
> 
> I just added some switches for device models, but it sounds like there might just be a bigger issue going on with the sensor in the 200S

Sorry for being off-topic, one question. What is your current value and how often does the value change? I think after fixing/setting the `status_poll_seconds` which is polling every n seconds it seems to work. But I am unsure if I can trust my values. I have in two different rooms `6.4 µg/m³`. My question is "how often does your value change?" and "how accurate are they if you compare multiple devices?"

Thanks in advance! :)

**Comment by Daemon125** [comment]
> @Daemon125
> 
> > At least on mine it's just purely that /10000. The 400S has a screen with PM2.5 readout independent from the firmware, so I'm using that as a reference. I'm occasionally seeing that timeout error as well though.
> > I just added some switches for device models, but it sounds like there might just be a bigger issue going on with the sensor in the 200S
> 
> Sorry for being off-topic, one question. What is your current value and how often does the value change? I think after fixing/setting the `status_poll_seconds` which is polling every n seconds it seems to work. But I am unsure if I can trust my values. I have in two different rooms `6.4 µg/m³`. My question is "how often does your value change?" and "how accurate are they if you compare multiple devices?"
> 
> Thanks in advance! :)

Living room (300s) - 22.0, Kitchen (400s) - 4.0, Loft (300s) - 1.0, Bedroom (300s) - 1.0
The variances are expected because I hit my vape near the living room. It's now back down to 1.0 as I'm typing this.

They only update every 30-60 seconds (I haven't timed it, but it's slow to pick up changes). I tried changing the poll value to 5 seconds with no luck, but based on your pull request that option is broken. I'll need to give it another shot with that line fixed

**Review by kerkmann — APPROVED** [review]

**Comment by SeveranExp** [comment]
OMG so this is why all of my air quality automations kept failing and I saw no pm values….

**Comment by kerkmann** [comment]
@Daemon125 The `levoit core 200s` has no `pm2.5`, your switch case isn't needed there. Sorry for the confusion. ^^"

See #28

**Comment by Daemon125** [comment]
@kerkmann Thank you for the confirmation. I just rolled it back to the original, only removing the /10000

**Comment by arthurtyukayev** [comment]
@acvigue Since you're checking in, this one would be good to merge in as well. This one is working as well.

**Comment by jojo01fr** [comment]
In the while I tested this commit and PM25 values went too low (1/10) compared with commit df394f8 that itself value is already 1/5 compared to an IKEA VINDSTYRKA in the same room 2 meter higher. Rolled back to that old commit that does not handle the Reset button and also puts the Levoit on ACK Timeouts after a few days obliging to plug off power in order to reset.
